### ISSUE TITLE
Android: Initializing only works once

### ISSUE THREAD

**Issue by cbenhagen** [hnvn/flutter_downloader#17]
```
I/flutter (19352): Caught error: MissingPluginException(No implementation found for method initialize on channel vn.hunghd/downloader)
I/flutter (19352): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
I/flutter (19352): <asynchronous suspension>
I/flutter (19352): #1      FlutterDownloader.initialize (package:flutter_downloader/flutter_downloader.dart:88:27)
I/flutter (19352): <asynchronous suspension>
```

**Comment by hoperuin** [comment]
Hi,try reopen project test.

**Comment by cbenhagen** [comment]
Just run initialize twice.

**Comment by hnvn** [comment]
This behavior is not expected by design. The plugin can be initialized one time and must be called before all other actions.

**Comment by cbenhagen** [comment]
Well even if you can only initialize once the user should at least be able to catch the error. When doing hot reloads it can sometimes happen that a widget or BLoC gets rebuilt and the code tries to re-init the plugin.
